# Build and run a Web deployment with WildFly
:toc:               left

## Build and run on local machine

### Build the application

We are using the `package` goal of the `org.wildfly.plugins:wildfly-maven-plugin` to provision WildFly and deploy the WAR on it.

You can build the application:

[source,bash]
----
$ mvn clean package
----

At the end of the Maven execution, the application (composed of WildFly and the WAR) has been created put in the `target/server` directory.

### Run the application

You can run the application with:

[source,bash]
----
$ ./target/server/bin/standalone.sh
...
15:22:47,744 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 27.0.0.Alpha5 (WildFly Core 19.0.0.Beta15) started in 5125ms - Started 261 of 358 services (145 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
----

Once the application is started, we can query it with:

[source,bash]
----
$ curl "http://localhost:8080/?value=3"
9
----

### Test the application

You can test the complete application (WildFly + deployment) using Arquillian.
Arquillian will manage the application and start it before the integration tests are run with:

[source,bash]
----
mvn clean verify
----

### Build the application image

We are using the `image` goal of the `org.wildfly.plugins:wildfly-maven-plugin` to create a container image that contains the application (WildFly + WAR)
This goal relies on a Docker binary (`docker` by default or `podman`) to perform the image commands.

We can build the application image:

[source,bash]
----
$ mvn clean package
...
[INFO] --- wildfly-maven-plugin:4.0.0.Beta4-SNAPSHOT:image (default) @ wildfly-demo ---
...
Successfully built application image wildfly-demo:latest
...
----

At the end of the Maven execution, the application image has been built with the name wildfly-demo:latest.

### Run the application image

We can run the application image with:

[source,bash]
----
$ docker run -p 8080:8080 wildfly-demo:latest
----

Once the image is started, we can query it with:

[source,bash]
----
$ curl "http://localhost:8080/?value=3"
9
----
